- .gitignore
- extensions/currencyExt/bootstrap.js
- extensions/currencyExt/graphql/types/Price/Price.resolvers.js
- extensions/currencyExt/pages/frontStore/all/[context]iso[detectCurrentCart].js
- packages/evershop/src/modules/checkout/api/addMineCartItem/[detectCurrentCart]addItemToCart.js
- packages/evershop/src/modules/checkout/api/createCart/createNewCart.js
- packages/evershop/src/modules/checkout/pages/frontStore/all/[context]detectCurrentCart[auth].js
- packages/evershop/src/modules/checkout/services/cart/registerCartBaseFields.js
- packages/evershop/src/modules/checkout/services/createNewCart.js
> [feat][store-front] GC-135: Customize Evershop feature to display price in selected currency

- extensions/facebook_login/api/createFacebookCustomer/[bodyParser]createFacebookCustomer.js
- extensions/facebook_login/api/createFacebookCustomer/[context]bodyParser[auth].js
- extensions/facebook_login/api/createFacebookCustomer/payloadSchema.json
- extensions/facebook_login/api/createFacebookCustomer/route.json
- extensions/facebook_login/config.example.json
- extensions/facebook_login/migration/Version-1.0.0.js
- extensions/facebook_login/package.json
- extensions/facebook_login/pages/frontStore/facebookAuth/[auth]facebookAuth.js
- extensions/facebook_login/pages/frontStore/facebookAuth/route.json
- extensions/facebook_login/pages/frontStore/facebookCallback/facebookCallback.js
- extensions/facebook_login/pages/frontStore/facebookCallback/route.json
- extensions/facebook_login/pages/frontStore/login/FacebookLogin.jsx
- extensions/facebook_login/pages/frontStore/login/FacebookLogin.scss
- extensions/facebook_login/services/getFacebookAuthToken.js
- extensions/facebook_login/services/getFacebookAuthUrl.js
- extensions/facebook_login/services/getFacebookUserInfo.js
- packages/evershop/src/modules/customer/constant/account-status.js
- packages/evershop/src/modules/customer/constant/index.js
- packages/evershop/src/modules/customer/constant/loginSource.js
JIRA Issue: [GC-232](https://gohub.atlassian.net/jira/software/c/projects/GC/boards/3?quickFilter=2&selectedIssue=GC-232)
> GC-232: Implement Facebook Login

- extensions/currency/migrations/Version-1.0.1.js
- packages/evershop/bin/lib/loadModules.js
- packages/evershop/src/modules/translation/api/createLanguage/[context]bodyParser[auth].js
- packages/evershop/src/modules/translation/api/createLanguage/createLanguage[finish].js
- packages/evershop/src/modules/translation/api/createLanguage/finish[apiResponse].js
- packages/evershop/src/modules/translation/api/createLanguage/payloadSchema.json
- packages/evershop/src/modules/translation/api/createLanguage/route.json
- packages/evershop/src/modules/translation/api/updateLanguage/[context]bodyParser[auth].js
- packages/evershop/src/modules/translation/api/updateLanguage/finish[apiResponse].js
- packages/evershop/src/modules/translation/api/updateLanguage/payloadSchema.json
- packages/evershop/src/modules/translation/api/updateLanguage/route.json
- packages/evershop/src/modules/translation/api/updateLanguage/updateLanguage[finish].js
- packages/evershop/src/modules/translation/graphql/types/Language/Language.admin.graphql
- packages/evershop/src/modules/translation/graphql/types/Language/Language.admin.resolvers.js
- packages/evershop/src/modules/translation/graphql/types/Language/Language.graphql
- packages/evershop/src/modules/translation/graphql/types/Language/Language.resolvers.js
- packages/evershop/src/modules/translation/migration/Version-1.0.0.js
- packages/evershop/src/modules/translation/services/language/createLanguage.js
- packages/evershop/src/modules/translation/services/language/getLanguagesBaseQuery.js
- packages/evershop/src/modules/translation/services/language/languageDataSchema.json
- packages/evershop/src/modules/translation/services/language/updateLanguage.js
JIRA Issue [GC-244: Setup Language API](https://gohub.atlassian.net/jira/software/c/projects/GC/boards/3?quickFilter=2&selectedIssue=GC-244)
> GC-244: Setup Language API (Admin & Customer)

- packages/evershop/src/modules/translation/api/createTranslation/[context]bodyParser[auth].js
- packages/evershop/src/modules/translation/api/createTranslation/createTranslation[finish].js
- packages/evershop/src/modules/translation/api/createTranslation/finish[apiResponse].js
- packages/evershop/src/modules/translation/api/createTranslation/payloadSchema.json
- packages/evershop/src/modules/translation/api/createTranslation/route.json
- packages/evershop/src/modules/translation/api/updateTranslation/[context]bodyParser[auth].js
- packages/evershop/src/modules/translation/api/updateTranslation/finish[apiResponse].js
- packages/evershop/src/modules/translation/api/updateTranslation/payloadSchema.json
- packages/evershop/src/modules/translation/api/updateTranslation/route.json
- packages/evershop/src/modules/translation/api/updateTranslation/updateTranslation[finish].js
- packages/evershop/src/modules/translation/graphql/types/Translation/Translation.admin.graphql
- packages/evershop/src/modules/translation/graphql/types/Translation/Translation.admin.resolvers.js
- packages/evershop/src/modules/translation/services/translation/createTranslation.js
- packages/evershop/src/modules/translation/services/translation/getTranslationsBaseQuery.js
- packages/evershop/src/modules/translation/services/translation/translationDataSchema.json
- packages/evershop/src/modules/translation/services/translation/updateTranslation.js
JIRA Issue [GC-245: Setup Translation API](https://gohub.atlassian.net/jira/software/c/projects/GC/boards/3?quickFilter=2&selectedIssue=GC-245)
> GC 245: Setup Translation API (Admin)

- extensions/currency/api/updateCurrency/finish[apiResponse].js
- extensions/currency/bootstrap.js
- extensions/currency/pages/admin/currencyGrid/Grid.jsx
- extensions/currency/services/currency/createCurrency.js
- extensions/currency/services/currency/updateCurrency.js
- packages/evershop/bin/lib/startUp.js
- packages/evershop/src/components/admin/catalog/collection/collectionEdit/AddProducts.jsx
- packages/evershop/src/components/admin/catalog/productEdit/variants/SubmitButton.jsx
- packages/evershop/src/components/admin/catalog/productEdit/variants/VariantModal.jsx
- packages/evershop/src/modules/catalog/api/addVariantItem/[bodyParser]addItem.js
- packages/evershop/src/modules/catalog/api/updateAttribute/finish[apiResponse].js
- packages/evershop/src/modules/catalog/graphql/types/Attribute/Attribute.admin.resolvers.js
- packages/evershop/src/modules/catalog/graphql/types/Category/Category.resolvers.js
- packages/evershop/src/modules/catalog/graphql/types/Product/Metadata/ProductMetadata.resolvers.js
- packages/evershop/src/modules/catalog/pages/admin/attributeEdit+attributeNew/General.jsx
- packages/evershop/src/modules/catalog/pages/admin/attributeGrid/Grid.jsx
- packages/evershop/src/modules/catalog/pages/admin/categoryGrid/Grid.jsx
- packages/evershop/src/modules/catalog/pages/admin/collectionEdit/Products.jsx
- packages/evershop/src/modules/catalog/pages/admin/productGrid/Grid.jsx
- packages/evershop/src/modules/checkout/graphql/types/Price/Price.resolvers.js
- packages/evershop/src/modules/checkout/services/currency/updateCurrency.js
> GC-237-chore: Remove console.log

- extensions/tazapay/api/tazapayCheckoutService/[auth]addCustomerToCart.js
- extensions/tazapay/api/tazapayCheckoutService/[context]bodyParser[auth].js
- extensions/tazapay/api/tazapayCheckoutService/[detectCurrentCart]placeOrder.js
- extensions/tazapay/api/tazapayCheckoutService/[getCurrentCustomer]detectCurrentCart.js
- extensions/tazapay/api/tazapayCheckoutService/payloadSchema.json
- extensions/tazapay/api/tazapayCheckoutService/route.json
- extensions/tazapay/api/tazapayWebHook/[bodyJson]webhook.js
- extensions/tazapay/api/tazapayWebHook/bodyJson.js
- extensions/tazapay/api/tazapayWebHook/route.json
- extensions/tazapay/graphql/types/TazapaySetting/TazapaySetting.admin.graphql
- extensions/tazapay/graphql/types/TazapaySetting/TazapaySetting.admin.resolvers.js
- extensions/tazapay/graphql/types/TazapaySetting/TazapaySetting.graphql
- extensions/tazapay/graphql/types/TazapaySetting/TazapaySetting.resolvers.js
- extensions/tazapay/pages/admin/paymentSetting/TazapayPayment.jsx
- extensions/tazapay/services/signature_generation.js
- extensions/tazapay/services/utils.js
- package.json
1.) place order
2.) webhook
todos:
- idempotency key to avoid duplicate order and transaction
- refactor code for readability
- important: use `axios` pkg instead of `https` pkg
> [feat] tazapay extension

- extensions/tazapay/pages/admin/paymentSetting/TazapayPayment.jsx
> [fix] render tazapay setting ui

- extensions/tazapay/api/tazapayRetry/[auth]retry.js
- extensions/tazapay/api/tazapayRetry/[context]bodyParser[auth].js
- extensions/tazapay/api/tazapayRetry/payloadSchema.json
- extensions/tazapay/api/tazapayRetry/route.json
- packages/evershop/src/modules/oms/graphql/types/Order/Order.resolvers.js
> [feat] retry tazapay payment api

- extensions/apple_login/api/createAppleCustomer/[bodyParser]createAppleCustomer.js
- extensions/apple_login/api/createAppleCustomer/[context]bodyParser[auth].js
- extensions/apple_login/api/createAppleCustomer/payloadSchema.json
- extensions/apple_login/api/createAppleCustomer/route.json
- extensions/apple_login/migration/Version-1.0.0.js
- extensions/apple_login/package.json
- extensions/apple_login/services/getAppleUserInfo.js
- extensions/apple_login/services/getDefaultCurrency.js
- extensions/apple_login/services/getDefaultLanguage.js
- extensions/apple_login/services/mapper/createCurrencyResponse.js
- extensions/apple_login/services/mapper/createLanguageResponse.js
- packages/evershop/src/modules/customer/constant/loginSource.js
> [feat] apple extension

- extensions/webhook/api/updateOrderStatus/[bodyParser]requireAuth.js
- extensions/webhook/api/updateOrderStatus/[context]bodyParser[auth].js
- extensions/webhook/api/updateOrderStatus/[requireAuth]updateOrderStatus.js
- extensions/webhook/api/updateOrderStatus/payloadSchema.json
- extensions/webhook/api/updateOrderStatus/route.json
- extensions/webhook/migration/Version-1.0.0.js
- extensions/webhook/package.json
- extensions/webhook/services/order.service.js
Jira Issue: [GC-213: Create endpoint in Evershop to receive the update from Gohub.Cloud for the fulfilment & the list of esims](https://gohub.atlassian.net/browse/GC-213)
> GC-213: Create endpoint in Evershop to receive the update from Gohub.Cloud for the fulfilment & the list of esims

- packages/evershop/src/modules/catalog/services/ProductCollection.js
- [x ] Refactoring (no functional changes, no api changes)
Description
Current
As attachment below, in the All tab, the sort order of product listing shows wrong order, in detail: 
Item with larger data amount appears first, then item with smaller data amount.
Acceptance Criteria
Right sort order of All tabs:
Local esim first
If not local esim:
Sort based on data amount (from smallest to largest).
If data amount == unlimited → arrange them at the end of the list.
Note:
Total data amount:
data-type = Fixed data → Total data amount = data amount
data-type = Daily data → Total data amount = data amount * day amount
> GA-91: Sort order product listing error

- packages/evershop/src/components/admin/cms/Card.scss
- packages/evershop/src/modules/setting/api/saveSetting/saveSetting.js
- packages/evershop/src/modules/setting/graphql/types/Setting/Setting.resolvers.js
- packages/evershop/src/modules/setting/graphql/types/SliderSetting/SliderSetting.admin.resolvers.js
- packages/evershop/src/modules/setting/graphql/types/SocialLinkSetting/SocialLinkSetting.graphql
- packages/evershop/src/modules/setting/graphql/types/SocialLinkSetting/SocialLinkSetting.resolvers.js
- packages/evershop/src/modules/setting/pages/admin/sliderSetting/SliderSetting.jsx
- packages/evershop/src/modules/setting/pages/admin/socialLinkSetting/SocialLinkSetting.jsx
**Description**
- Fixed cannot access admin setting page to config social links.
- Implement delete social link settings & slider settings
- Improve settings response on Get Setting API
> Add delete slider & social config

- packages/evershop/src/components/admin/promotion/couponEdit/Setting.jsx
- packages/evershop/src/modules/checkout/graphql/types/Cart/Cart.graphql
- packages/evershop/src/modules/checkout/graphql/types/Cart/Cart.resolvers.js
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.graphql
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
- packages/evershop/src/modules/promotion/migration/Version-1.0.2.js
- packages/evershop/src/modules/promotion/pages/admin/couponEdit+couponNew/General.jsx
- packages/evershop/src/modules/promotion/services/coupon/createCoupon.js
> [GC-833] Coupon management

- extensions/adyen/api/adyenPlaceOrder/[detectCurrentCart]placeOrder.js
- extensions/adyen/api/adyenPlaceOrder/payloadSchema.json
- extensions/checkoutApi/services/orderCreator.js
- extensions/eSim/api/eSimWebhook/[bodyJson]webhook.js
- extensions/eSim/services/esim.service.js
- extensions/tazapay/api/tazapayCheckoutService/[detectCurrentCart]placeOrder.js
- extensions/tazapay/api/tazapayCheckoutService/payloadSchema.json
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.admin.graphql
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.graphql
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
- packages/evershop/src/modules/promotion/migration/Version-1.0.2.js
- packages/evershop/src/modules/promotion/services/CouponCollection.js
> Feature: Place order with coupon

- extensions/checkoutApi/graphql/types/Cart/Cart.graphql
- extensions/checkoutApi/graphql/types/Cart/Cart.resolvers.js
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.graphql
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
> [feat] add img for coupon

- extensions/checkoutApi/graphql/types/Cart/Cart.resolvers.js
- packages/evershop/src/components/admin/promotion/couponEdit/Image.jsx
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
- packages/evershop/src/modules/promotion/pages/admin/couponEdit+couponNew/General.jsx
- packages/evershop/src/modules/promotion/services/coupon/couponDataSchema.json
- packages/evershop/src/modules/promotion/services/coupon/updateCoupon.js
> [feat] coupon img management

- extensions/checkoutApi/graphql/types/Cart/Cart.resolvers.js
- extensions/eSim/api/eSimWebhook/[bodyJson]webhook.js
- extensions/eSim/services/esim.service.js
- extensions/eSim/services/order.service.js
- extensions/webhook/services/order.service.js
> [fix] fulfil esim with order ref have AP prefix

- packages/evershop/src/modules/promotion/services/registerDefaultValidators.js
> [fix] error of evershop typeorm

- packages/evershop/src/components/admin/promotion/couponEdit/Image.jsx
> [fix] save url img

- packages/evershop/src/components/admin/promotion/couponEdit/Image.jsx
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
> [fix] crash update img coupon

- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
> [fix] check coupon stt

- packages/evershop/src/modules/promotion/services/coupon/createCoupon.js
> [fix] create new coupon

- extensions/eSim/graphql/types/Esim/eSim.graphql
- extensions/eSim/graphql/types/Esim/eSim.resolvers.js
- extensions/eSim/services/esim.service.js
> [fix] add dataType for esim details/list

- extensions/eSim/graphql/types/Esim/eSim.resolvers.js
- extensions/eSim/services/esim.service.js
- extensions/eSim/services/order.service.js
> [fix] module not found

- extensions/adyen/api/adyenPaymentDetails/[bodyParser]adyenPaymentDetails.js
- extensions/adyen/api/adyenPlaceOrder/[detectCurrentCart]placeOrder.js
- extensions/checkoutApi/graphql/types/Cart/Cart.graphql
- extensions/checkoutApi/graphql/types/Cart/Cart.resolvers.js
- extensions/tazapay/api/tazapayCheckoutService/[detectCurrentCart]placeOrder.js
- packages/evershop/src/modules/base/services/errorCode.js
> [feat] add errorCode to coupon applied cart response

- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.graphql
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
- packages/evershop/src/modules/promotion/migration/Version-1.0.3.js
- packages/evershop/src/modules/promotion/pages/admin/couponEdit+couponNew/General.jsx
- packages/evershop/src/modules/promotion/services/coupon/couponDataSchema.json
- packages/evershop/src/modules/promotion/services/coupon/createCoupon.js
- packages/evershop/src/modules/promotion/services/registerDefaultCouponCollectionFilters.js
> [feat] add private config for coupon

- packages/evershop/src/modules/promotion/services/registerDefaultCouponCollectionFilters.js
> [fix] uppercase coupon input

- extensions/adyen/api/adyenWebHook/[bodyJson]webhook.js
- extensions/adyen/services/adyen.service.js
- extensions/tazapay/api/tazapayCheckoutService/[detectCurrentCart]placeOrder.js
- extensions/tazapay/api/tazapayWebHook/[bodyJson]webhook.js
> [fix] replace order uuid with order number

- packages/evershop/src/modules/customer/api/global/[context]getCurrentCustomer[auth].js
- packages/evershop/src/modules/customer/graphql/types/Customer/Customer.graphql
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
- packages/evershop/src/modules/promotion/services/CouponCollection.js
> [fix] search private coupon

- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.resolvers.js
- packages/evershop/src/modules/promotion/services/CouponCollection.js
> [fix] private coupon

- packages/evershop/src/modules/customer/api/updateProfile/[bodyParser]updateProfile.js
> [fix] validate isFirstLogin

- extensions/adyen/api/adyenWebHook/[bodyJson]webhook.js
- extensions/tazapay/api/tazapayRetry/[auth]retry.js
- extensions/webhook/subscribers/reward_coupon/reward-coupon.js
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.admin.graphql
- packages/evershop/src/modules/promotion/graphql/types/Coupon/Coupon.admin.resolvers.js
- packages/evershop/src/modules/promotion/pages/admin/couponGrid/Grid.jsx
> Feat/draft referral UI

- extensions/checkoutApi/graphql/types/Cart/Cart.resolvers.js
> [refactor] rollback cart schema

- extensions/checkoutApi/graphql/types/Cart/Cart.graphql
> [fix] response cart schema

- extensions/checkoutApi/services/orderCreator.js
> [fix] generate orderRef with prefix
